"""empty message

Revision ID: 3a2c72f262b5
Revises: 15dd8689e7fe
Create Date: 2018-09-08 15:36:21.034476

"""

# revision identifiers, used by Alembic.
revision = '3a2c72f262b5'
down_revision = '15dd8689e7fe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_key', sa.Column('number_of_uses', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('print_key', 'number_of_uses', server_default=None)
    op.add_column('print_key', sa.Column('senders', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.alter_column('print_key', 'senders', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('print_key', 'senders')
    op.drop_column('print_key', 'number_of_uses')
    ### end Alembic commands ###
