"""empty message

Revision ID: 44c4368c2db1
Revises: 3a2c72f262b5
Create Date: 2018-09-08 16:06:27.267732

"""

# revision identifiers, used by Alembic.
revision = '44c4368c2db1'
down_revision = '3a2c72f262b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_key', sa.Column('parent_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('print_key', 'parent_id')
    ### end Alembic commands ###
